---
title: "Half_Model"
author: "JT Miller"
date: "5/27/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Libraries
```{r}
library(deSolve)
library(rootSolve)
```

### Here Im conducting a stability analysis on my model where only one bee is present
```{r}
Half.Bee.Model <- function(t,x,params){
  # State Variables 
  N = x[1]
  S = x[2]
  D = x[3]
  # Parameters
  phi = params[1]
  Ys = params[2]
  Us = params[3]
  hs = params[4]
  ms = params[5] 
  r = params[6] 
  Kd = params[7]
  xreq = params[8]
  delta = params[9]
  # The Equations
  dNdt = D*phi - (1/Ys)*((Us*N*S)/(1+Us*hs*N))
  
  dSdt = S*((Us*N)/(1 + Us*hs*N)) - S*ms
  
  dDdt = r*((S*delta/xreq)/(1 + (S*delta/xreq)))*D*(1 - D/Kd)
  
  return(list(c(dNdt, dSdt, dDdt)))
}

```

```{r}
### Setting up the parameters
phi = 100
Ys = 0.1
Us = 0.1
hs = 5
ms = 0.1
Kd = 1000
delta = 2 
xreq = 100
r = 0.05

parameters = c(phi, Ys, Us, hs,  ms, r, Kd, xreq, delta )

### Initial State Variable Values
N0 = 100
S0 = 10
D0 = 10


initial_values = c(N0,S0, D0)

# Set up the time
times <- seq(0, 500, by = 1) 

```

```{r}
Half.Bee.Model(times, initial_values, parameters)

results = lsoda(initial_values, times, Half.Bee.Model, parameters)

colnames(results) = c("time", "N", "S","D")

results
```
```{r}
# Plotting in base plot
plot(results[, "time"], results[, "N"], type="l", col="orange",  
     xlab="time", ylab="Quantity",ylim=c(0, max(results[, "S"]) + 100)) 

lines(results[, "time"], results[, "S"], type="l", col="blue")
lines(results[, "time"], results[, "D"], type="l", col="brown")


legend("topright", legend=c("N", "S", "D"), fill=c("orange", "blue", "brown"))
```
### Jacobian Matrix 
```{r}
Bee.Half.Equils <- function(x, params){
  # State Variables 
  N = x[1]
  S = x[2]
  D = x[3]
  # Parameters
  phi = params[1]
  Ys = params[2]
  Us = params[3]
  hs = params[4]
  ms = params[5] 
  r = params[6] 
  Kd = params[7]
  xreq = params[8]
  delta = params[9]
   # The Equations
  c(F1 = D*phi - (1/Ys)*((Us*N*S)/(1+Us*hs*N)),
  
 F2 = S*((Us*N)/(1 + Us*hs*N)) - S*ms,
  
 F3 = r*((S*delta/xreq)/(1 + (S*delta/xreq)))*D*(1 - D/Kd))
}

# Initial Values
x <- c(N0 = 1,S0 = 100000,D0 = 1000)

#call multiroot
eqm = multiroot(Bee.Half.Equils, x, parms = parameters)

#the equilibrium values are stored in the root part of eqm
eqm$root

# Numerically Calculate the Jacobian matrix at the equilibrium. 
JAC = jacobian.full(y=c(eqm$root), func = Half.Bee.Model, parms = parameters)
JAC

```
### Well this is unfortunate, the values chosen are apparently unstable at many points

### Tried dimensionless form, my algebra skills need some work, lets do this the brute force method. 
```{r}
ms_set <- seq(from=0.01, to = 0.99, by = 0.01)

for(j in 1:length(ms_set)){
  
  ms <- ms_set[j]
  
  for(i in 1:length(ms_set)){
    
    Bee.Half.Equils()
  }
}
```

